# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlist.proto\x12\x04main\"<\n\x0bItemRequest\x12\r\n\x05group\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04item\x18\x03 \x01(\t\"0\n\x0cItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"k\n\x06Update\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.main.Update.UpdateType\x12\x0c\n\x04item\x18\x02 \x01(\t\",\n\nUpdateType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\t\n\x05\x43HECK\x10\x02\"/\n\x0cItemsRequest\x12\r\n\x05group\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63hecked\x18\x02 \x01(\x08\"K\n\rItemsResponse\x12\r\n\x05group\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x19\n\x05items\x18\x03 \x03(\x0b\x32\n.main.Item\"3\n\x10SubscribeRequest\x12\r\n\x05group\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\x0cGroupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\rGroupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x89\x03\n\x0bListService\x12\x30\n\x07\x41\x64\x64Item\x12\x11.main.ItemRequest\x1a\x12.main.ItemResponse\x12\x32\n\tCheckItem\x12\x11.main.ItemRequest\x1a\x12.main.ItemResponse\x12\x33\n\x08GetItems\x12\x12.main.ItemsRequest\x1a\x13.main.ItemsResponse\x12\x33\n\nDeleteItem\x12\x11.main.ItemRequest\x1a\x12.main.ItemResponse\x12\x34\n\tJoinGroup\x12\x12.main.GroupRequest\x1a\x13.main.GroupResponse\x12\x36\n\x0b\x43reateGroup\x12\x12.main.GroupRequest\x1a\x13.main.GroupResponse\x12<\n\x12SubscribeToUpdates\x12\x16.main.SubscribeRequest\x1a\x0c.main.Update0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'list_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMREQUEST._serialized_start=20
  _ITEMREQUEST._serialized_end=80
  _ITEMRESPONSE._serialized_start=82
  _ITEMRESPONSE._serialized_end=130
  _UPDATE._serialized_start=132
  _UPDATE._serialized_end=239
  _UPDATE_UPDATETYPE._serialized_start=195
  _UPDATE_UPDATETYPE._serialized_end=239
  _ITEMSREQUEST._serialized_start=241
  _ITEMSREQUEST._serialized_end=288
  _ITEM._serialized_start=290
  _ITEM._serialized_end=327
  _ITEMSRESPONSE._serialized_start=329
  _ITEMSRESPONSE._serialized_end=404
  _SUBSCRIBEREQUEST._serialized_start=406
  _SUBSCRIBEREQUEST._serialized_end=457
  _GROUPREQUEST._serialized_start=459
  _GROUPREQUEST._serialized_end=505
  _GROUPRESPONSE._serialized_start=507
  _GROUPRESPONSE._serialized_end=539
  _LISTSERVICE._serialized_start=542
  _LISTSERVICE._serialized_end=935
# @@protoc_insertion_point(module_scope)
