# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlist.proto\x12\x04main\"*\n\x0bItemRequest\x12\r\n\x05group\x18\x01 \x01(\t\x12\x0c\n\x04item\x18\x02 \x01(\t\"\x1f\n\x0cItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1d\n\x0cItemsRequest\x12\r\n\x05group\x18\x01 \x01(\t\"\x1e\n\rItemsResponse\x12\r\n\x05items\x18\x01 \x03(\t2t\n\x0bListService\x12\x30\n\x07\x41\x64\x64Item\x12\x11.main.ItemRequest\x1a\x12.main.ItemResponse\x12\x33\n\x08GetItems\x12\x12.main.ItemsRequest\x1a\x13.main.ItemsResponseb\x06proto3')



_ITEMREQUEST = DESCRIPTOR.message_types_by_name['ItemRequest']
_ITEMRESPONSE = DESCRIPTOR.message_types_by_name['ItemResponse']
_ITEMSREQUEST = DESCRIPTOR.message_types_by_name['ItemsRequest']
_ITEMSRESPONSE = DESCRIPTOR.message_types_by_name['ItemsResponse']
ItemRequest = _reflection.GeneratedProtocolMessageType('ItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMREQUEST,
  '__module__' : 'list_pb2'
  # @@protoc_insertion_point(class_scope:main.ItemRequest)
  })
_sym_db.RegisterMessage(ItemRequest)

ItemResponse = _reflection.GeneratedProtocolMessageType('ItemResponse', (_message.Message,), {
  'DESCRIPTOR' : _ITEMRESPONSE,
  '__module__' : 'list_pb2'
  # @@protoc_insertion_point(class_scope:main.ItemResponse)
  })
_sym_db.RegisterMessage(ItemResponse)

ItemsRequest = _reflection.GeneratedProtocolMessageType('ItemsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSREQUEST,
  '__module__' : 'list_pb2'
  # @@protoc_insertion_point(class_scope:main.ItemsRequest)
  })
_sym_db.RegisterMessage(ItemsRequest)

ItemsResponse = _reflection.GeneratedProtocolMessageType('ItemsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSRESPONSE,
  '__module__' : 'list_pb2'
  # @@protoc_insertion_point(class_scope:main.ItemsResponse)
  })
_sym_db.RegisterMessage(ItemsResponse)

_LISTSERVICE = DESCRIPTOR.services_by_name['ListService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMREQUEST._serialized_start=20
  _ITEMREQUEST._serialized_end=62
  _ITEMRESPONSE._serialized_start=64
  _ITEMRESPONSE._serialized_end=95
  _ITEMSREQUEST._serialized_start=97
  _ITEMSREQUEST._serialized_end=126
  _ITEMSRESPONSE._serialized_start=128
  _ITEMSRESPONSE._serialized_end=158
  _LISTSERVICE._serialized_start=160
  _LISTSERVICE._serialized_end=276
# @@protoc_insertion_point(module_scope)
